---SQL Create Table Commands Written by Tran Le 

DROP TABLE STUDENTENROLLMENT;
DROP TABLE COURSE; 
DROP TABLE INSTRUCTOR;
DROP TABLE STUDENT;


CREATE TABLE COURSE
(
COURSEID 		INTEGER PRIMARY KEY,
COURSENAME 		VARCHAR2(15),
COURSEBLDG 		VARCHAR2(20),
COURSEROOM 		VARCHAR2(20),
COURSECAPACITY 	INTEGER);

CREATE TABLE INSTRUCTOR
(
INSTRID 	INTEGER PRIMARY KEY,
INSTRNAME 	VARCHAR2(25),
INSTRPREFIX VARCHAR2(5),
INSTROFFICE VARCHAR2(25),
INSTRDEPT 	VARCHAR2(20), 
INSTREMAIL 	VARCHAR2(25)); 

CREATE TABLE STUDENT
(
STUDENTID 		INTEGER PRIMARY KEY,
STUDENTNAME 	VARCHAR2(25),
STUDENTYEAR 	NUMBER,
STUDENTMAJOR 	VARCHAR2(20),
STUDENTGPA 		NUMBER,
STUDENTEMAIL 	VARCHAR2(20)); 

CREATE TABLE STUDENTENROLLMENT
(
COURSEID 	INTEGER, 
STUDENTID 	INTEGER,
FOREIGN KEY (COURSEID) 	REFERENCES COURSE,
FOREIGN KEY (STUDENTID) REFERENCES STUDENT,
PRIMARY KEY	(COURSEID,STUDENTID)); 